In [170]:
import numpy as np

# Exercises

In [171]:
# https://glowingpython.blogspot.com/2011/05/four-ways-to-compute-google-pagerank.html
def get_eigenvector(A):
    n = A.shape[1]
    _, v = np.linalg.eig(A)
    
    return np.abs(np.real(v[:n, 0]) / np.linalg.norm(v[:n, 0], 1))

## Exercise 1

In [172]:
A = np.array([
    [0,   0,   1,   1/2, 0],
    [1/3, 0,   0,   0,   0],
    [1/3, 1/2, 0,   1/2, 1],
    [1/3, 1/2, 0,   0,   0],
    [0,   0,   1/2, 0,   0]
])

vector = get_eigenvector(A)
print(vector)

[0.32671498 0.09430017 0.30975165 0.13512715 0.13410604]


It would appear that page 3's score has increased, but not above that of page 1.
If a page 5 is added, the following two items will happen:
    1. The "vote" of page 3 will now split between page 1 and page 5, therefore reducing page 1's score
    2. The "vote" of page 5 will boost the score of page 3.

## Exercise 2

In [173]:
A = np.array([
    [0, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 1/2],
    [0, 0, 0, 0, 1, 0, 1/2],
    [0, 0, 0, 0, 0, 0, 0]
])

eigenvalues, _ = np.linalg.eig(A)

print(eigenvalues, len(np.where(eigenvalues == 1)[0]))

[ 1. -1.  1. -1.  1. -1.  0.] 3


The example web has 3 separate subwebs, similar to figure 2.2. 
As you can see, there are three eigenvalues equal to 1. This demonstrates 
that the dimension of V_1(A) equals (or exceeds) the number of components in the web.

## Exercise 3

In [174]:
A = np.array([
    [0, 1, 0, 0, 1/3],
    [1, 0, 0, 0, 0],
    [0, 0, 0, 1, 1/3],
    [0, 0, 1, 0, 1/3],
    [0, 0, 0, 0, 0],
])

eigenvalues, _ = np.linalg.eig(A)

print(eigenvalues, len(np.where(eigenvalues == 1)[0]))

[ 1. -1.  1. -1.  0.] 2


## Exercise 4

## Exercise 5

## Exercise 6

## Exercise 7

## Exercise 8

## Exercise 9

## Exercise 10

## Exercise 11

## Exercise 12

## Exercise 13

## Exercise 14

## Exercise 15

## Exercise 16

## Exercise 17